version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      minor-production:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      minor-development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 10
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
